//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("avfun_DAL_model", "FK_NEWS_ADMIN", "ADMIN", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AvFun_Website.Avfun_DAL.ADMIN), "NEWS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AvFun_Website.Avfun_DAL.NEWS), true)]
[assembly: EdmRelationshipAttribute("avfun_DAL_model", "FK_ORDER_COURSE", "COURSE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AvFun_Website.Avfun_DAL.COURSE), "ORDER", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AvFun_Website.Avfun_DAL.ORDER), true)]
[assembly: EdmRelationshipAttribute("avfun_DAL_model", "FK_REVIEW_NEWS", "NEWS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AvFun_Website.Avfun_DAL.NEWS), "REVIEW", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AvFun_Website.Avfun_DAL.REVIEW), true)]
[assembly: EdmRelationshipAttribute("avfun_DAL_model", "FK_ORDER_USER", "USER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AvFun_Website.Avfun_DAL.USER), "ORDER", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AvFun_Website.Avfun_DAL.ORDER), true)]
[assembly: EdmRelationshipAttribute("avfun_DAL_model", "FK_REVIEW_USER", "USER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AvFun_Website.Avfun_DAL.USER), "REVIEW", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AvFun_Website.Avfun_DAL.REVIEW), true)]

#endregion

namespace AvFun_Website.Avfun_DAL
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class avfunEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“avfunEntities”部分中的连接字符串初始化新 avfunEntities 对象。
        /// </summary>
        public avfunEntities() : base("name=avfunEntities", "avfunEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 avfunEntities 对象。
        /// </summary>
        public avfunEntities(string connectionString) : base(connectionString, "avfunEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 avfunEntities 对象。
        /// </summary>
        public avfunEntities(EntityConnection connection) : base(connection, "avfunEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ADMIN> ADMIN
        {
            get
            {
                if ((_ADMIN == null))
                {
                    _ADMIN = base.CreateObjectSet<ADMIN>("ADMIN");
                }
                return _ADMIN;
            }
        }
        private ObjectSet<ADMIN> _ADMIN;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<COURSE> COURSE
        {
            get
            {
                if ((_COURSE == null))
                {
                    _COURSE = base.CreateObjectSet<COURSE>("COURSE");
                }
                return _COURSE;
            }
        }
        private ObjectSet<COURSE> _COURSE;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<NEWS> NEWS
        {
            get
            {
                if ((_NEWS == null))
                {
                    _NEWS = base.CreateObjectSet<NEWS>("NEWS");
                }
                return _NEWS;
            }
        }
        private ObjectSet<NEWS> _NEWS;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ORDER> ORDER
        {
            get
            {
                if ((_ORDER == null))
                {
                    _ORDER = base.CreateObjectSet<ORDER>("ORDER");
                }
                return _ORDER;
            }
        }
        private ObjectSet<ORDER> _ORDER;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<REVIEW> REVIEW
        {
            get
            {
                if ((_REVIEW == null))
                {
                    _REVIEW = base.CreateObjectSet<REVIEW>("REVIEW");
                }
                return _REVIEW;
            }
        }
        private ObjectSet<REVIEW> _REVIEW;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<USER> USER
        {
            get
            {
                if ((_USER == null))
                {
                    _USER = base.CreateObjectSet<USER>("USER");
                }
                return _USER;
            }
        }
        private ObjectSet<USER> _USER;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<AdminNewsList> AdminNewsList
        {
            get
            {
                if ((_AdminNewsList == null))
                {
                    _AdminNewsList = base.CreateObjectSet<AdminNewsList>("AdminNewsList");
                }
                return _AdminNewsList;
            }
        }
        private ObjectSet<AdminNewsList> _AdminNewsList;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 ADMIN EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToADMIN(ADMIN aDMIN)
        {
            base.AddObject("ADMIN", aDMIN);
        }
    
        /// <summary>
        /// 用于向 COURSE EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToCOURSE(COURSE cOURSE)
        {
            base.AddObject("COURSE", cOURSE);
        }
    
        /// <summary>
        /// 用于向 NEWS EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToNEWS(NEWS nEWS)
        {
            base.AddObject("NEWS", nEWS);
        }
    
        /// <summary>
        /// 用于向 ORDER EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToORDER(ORDER oRDER)
        {
            base.AddObject("ORDER", oRDER);
        }
    
        /// <summary>
        /// 用于向 REVIEW EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToREVIEW(REVIEW rEVIEW)
        {
            base.AddObject("REVIEW", rEVIEW);
        }
    
        /// <summary>
        /// 用于向 USER EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUSER(USER uSER)
        {
            base.AddObject("USER", uSER);
        }
    
        /// <summary>
        /// 用于向 AdminNewsList EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToAdminNewsList(AdminNewsList adminNewsList)
        {
            base.AddObject("AdminNewsList", adminNewsList);
        }

        #endregion
        #region 函数导入
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        /// <param name="orderPrice">没有元数据文档可用。</param>
        /// <param name="orderUser">没有元数据文档可用。</param>
        /// <param name="orderCourse">没有元数据文档可用。</param>
        /// <param name="orderIsPaid">没有元数据文档可用。</param>
        public int CreateNewOrder(Nullable<global::System.Double> orderPrice, Nullable<global::System.Guid> orderUser, Nullable<global::System.Guid> orderCourse, global::System.Byte[] orderIsPaid)
        {
            ObjectParameter orderPriceParameter;
            if (orderPrice.HasValue)
            {
                orderPriceParameter = new ObjectParameter("OrderPrice", orderPrice);
            }
            else
            {
                orderPriceParameter = new ObjectParameter("OrderPrice", typeof(global::System.Double));
            }
    
            ObjectParameter orderUserParameter;
            if (orderUser.HasValue)
            {
                orderUserParameter = new ObjectParameter("OrderUser", orderUser);
            }
            else
            {
                orderUserParameter = new ObjectParameter("OrderUser", typeof(global::System.Guid));
            }
    
            ObjectParameter orderCourseParameter;
            if (orderCourse.HasValue)
            {
                orderCourseParameter = new ObjectParameter("OrderCourse", orderCourse);
            }
            else
            {
                orderCourseParameter = new ObjectParameter("OrderCourse", typeof(global::System.Guid));
            }
    
            ObjectParameter orderIsPaidParameter;
            if (orderIsPaid != null)
            {
                orderIsPaidParameter = new ObjectParameter("OrderIsPaid", orderIsPaid);
            }
            else
            {
                orderIsPaidParameter = new ObjectParameter("OrderIsPaid", typeof(global::System.Byte[]));
            }
    
            return base.ExecuteFunction("CreateNewOrder", orderPriceParameter, orderUserParameter, orderCourseParameter, orderIsPaidParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="avfun_DAL_model", Name="ADMIN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ADMIN : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ADMIN 对象。
        /// </summary>
        /// <param name="a_id">a_id 属性的初始值。</param>
        /// <param name="admin_id">admin_id 属性的初始值。</param>
        /// <param name="admin_account">admin_account 属性的初始值。</param>
        /// <param name="admin_password">admin_password 属性的初始值。</param>
        /// <param name="admin_last_login_time">admin_last_login_time 属性的初始值。</param>
        /// <param name="admin_last_login_ip">admin_last_login_ip 属性的初始值。</param>
        /// <param name="admin_nickname">admin_nickname 属性的初始值。</param>
        /// <param name="admin_timestamp">admin_timestamp 属性的初始值。</param>
        public static ADMIN CreateADMIN(global::System.Int32 a_id, global::System.Guid admin_id, global::System.String admin_account, global::System.String admin_password, global::System.DateTime admin_last_login_time, global::System.String admin_last_login_ip, global::System.String admin_nickname, global::System.Byte[] admin_timestamp)
        {
            ADMIN aDMIN = new ADMIN();
            aDMIN.a_id = a_id;
            aDMIN.admin_id = admin_id;
            aDMIN.admin_account = admin_account;
            aDMIN.admin_password = admin_password;
            aDMIN.admin_last_login_time = admin_last_login_time;
            aDMIN.admin_last_login_ip = admin_last_login_ip;
            aDMIN.admin_nickname = admin_nickname;
            aDMIN.admin_timestamp = admin_timestamp;
            return aDMIN;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 a_id
        {
            get
            {
                return _a_id;
            }
            set
            {
                Ona_idChanging(value);
                ReportPropertyChanging("a_id");
                _a_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("a_id");
                Ona_idChanged();
            }
        }
        private global::System.Int32 _a_id;
        partial void Ona_idChanging(global::System.Int32 value);
        partial void Ona_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid admin_id
        {
            get
            {
                return _admin_id;
            }
            set
            {
                if (_admin_id != value)
                {
                    Onadmin_idChanging(value);
                    ReportPropertyChanging("admin_id");
                    _admin_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("admin_id");
                    Onadmin_idChanged();
                }
            }
        }
        private global::System.Guid _admin_id;
        partial void Onadmin_idChanging(global::System.Guid value);
        partial void Onadmin_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String admin_account
        {
            get
            {
                return _admin_account;
            }
            set
            {
                Onadmin_accountChanging(value);
                ReportPropertyChanging("admin_account");
                _admin_account = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("admin_account");
                Onadmin_accountChanged();
            }
        }
        private global::System.String _admin_account;
        partial void Onadmin_accountChanging(global::System.String value);
        partial void Onadmin_accountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String admin_password
        {
            get
            {
                return _admin_password;
            }
            set
            {
                Onadmin_passwordChanging(value);
                ReportPropertyChanging("admin_password");
                _admin_password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("admin_password");
                Onadmin_passwordChanged();
            }
        }
        private global::System.String _admin_password;
        partial void Onadmin_passwordChanging(global::System.String value);
        partial void Onadmin_passwordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime admin_last_login_time
        {
            get
            {
                return _admin_last_login_time;
            }
            set
            {
                Onadmin_last_login_timeChanging(value);
                ReportPropertyChanging("admin_last_login_time");
                _admin_last_login_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("admin_last_login_time");
                Onadmin_last_login_timeChanged();
            }
        }
        private global::System.DateTime _admin_last_login_time;
        partial void Onadmin_last_login_timeChanging(global::System.DateTime value);
        partial void Onadmin_last_login_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String admin_last_login_ip
        {
            get
            {
                return _admin_last_login_ip;
            }
            set
            {
                Onadmin_last_login_ipChanging(value);
                ReportPropertyChanging("admin_last_login_ip");
                _admin_last_login_ip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("admin_last_login_ip");
                Onadmin_last_login_ipChanged();
            }
        }
        private global::System.String _admin_last_login_ip;
        partial void Onadmin_last_login_ipChanging(global::System.String value);
        partial void Onadmin_last_login_ipChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String admin_nickname
        {
            get
            {
                return _admin_nickname;
            }
            set
            {
                Onadmin_nicknameChanging(value);
                ReportPropertyChanging("admin_nickname");
                _admin_nickname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("admin_nickname");
                Onadmin_nicknameChanged();
            }
        }
        private global::System.String _admin_nickname;
        partial void Onadmin_nicknameChanging(global::System.String value);
        partial void Onadmin_nicknameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] admin_timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_admin_timestamp);
            }
            set
            {
                Onadmin_timestampChanging(value);
                ReportPropertyChanging("admin_timestamp");
                _admin_timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("admin_timestamp");
                Onadmin_timestampChanged();
            }
        }
        private global::System.Byte[] _admin_timestamp;
        partial void Onadmin_timestampChanging(global::System.Byte[] value);
        partial void Onadmin_timestampChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("avfun_DAL_model", "FK_NEWS_ADMIN", "NEWS")]
        public EntityCollection<NEWS> NEWS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NEWS>("avfun_DAL_model.FK_NEWS_ADMIN", "NEWS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NEWS>("avfun_DAL_model.FK_NEWS_ADMIN", "NEWS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="avfun_DAL_model", Name="AdminNewsList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AdminNewsList : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 AdminNewsList 对象。
        /// </summary>
        /// <param name="admin_nickname">admin_nickname 属性的初始值。</param>
        /// <param name="news_id">news_id 属性的初始值。</param>
        /// <param name="news_title">news_title 属性的初始值。</param>
        /// <param name="news_publish_date">news_publish_date 属性的初始值。</param>
        /// <param name="news_isDeleted">news_isDeleted 属性的初始值。</param>
        /// <param name="news_isOnIndex">news_isOnIndex 属性的初始值。</param>
        /// <param name="news_image">news_image 属性的初始值。</param>
        /// <param name="news_click_count">news_click_count 属性的初始值。</param>
        /// <param name="news_content">news_content 属性的初始值。</param>
        /// <param name="news_author">news_author 属性的初始值。</param>
        public static AdminNewsList CreateAdminNewsList(global::System.String admin_nickname, global::System.Guid news_id, global::System.String news_title, global::System.DateTime news_publish_date, global::System.Boolean news_isDeleted, global::System.Boolean news_isOnIndex, global::System.String news_image, global::System.Int32 news_click_count, global::System.String news_content, global::System.Guid news_author)
        {
            AdminNewsList adminNewsList = new AdminNewsList();
            adminNewsList.admin_nickname = admin_nickname;
            adminNewsList.news_id = news_id;
            adminNewsList.news_title = news_title;
            adminNewsList.news_publish_date = news_publish_date;
            adminNewsList.news_isDeleted = news_isDeleted;
            adminNewsList.news_isOnIndex = news_isOnIndex;
            adminNewsList.news_image = news_image;
            adminNewsList.news_click_count = news_click_count;
            adminNewsList.news_content = news_content;
            adminNewsList.news_author = news_author;
            return adminNewsList;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String admin_nickname
        {
            get
            {
                return _admin_nickname;
            }
            set
            {
                if (_admin_nickname != value)
                {
                    Onadmin_nicknameChanging(value);
                    ReportPropertyChanging("admin_nickname");
                    _admin_nickname = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("admin_nickname");
                    Onadmin_nicknameChanged();
                }
            }
        }
        private global::System.String _admin_nickname;
        partial void Onadmin_nicknameChanging(global::System.String value);
        partial void Onadmin_nicknameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid news_id
        {
            get
            {
                return _news_id;
            }
            set
            {
                if (_news_id != value)
                {
                    Onnews_idChanging(value);
                    ReportPropertyChanging("news_id");
                    _news_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("news_id");
                    Onnews_idChanged();
                }
            }
        }
        private global::System.Guid _news_id;
        partial void Onnews_idChanging(global::System.Guid value);
        partial void Onnews_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String news_title
        {
            get
            {
                return _news_title;
            }
            set
            {
                if (_news_title != value)
                {
                    Onnews_titleChanging(value);
                    ReportPropertyChanging("news_title");
                    _news_title = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("news_title");
                    Onnews_titleChanged();
                }
            }
        }
        private global::System.String _news_title;
        partial void Onnews_titleChanging(global::System.String value);
        partial void Onnews_titleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime news_publish_date
        {
            get
            {
                return _news_publish_date;
            }
            set
            {
                if (_news_publish_date != value)
                {
                    Onnews_publish_dateChanging(value);
                    ReportPropertyChanging("news_publish_date");
                    _news_publish_date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("news_publish_date");
                    Onnews_publish_dateChanged();
                }
            }
        }
        private global::System.DateTime _news_publish_date;
        partial void Onnews_publish_dateChanging(global::System.DateTime value);
        partial void Onnews_publish_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean news_isDeleted
        {
            get
            {
                return _news_isDeleted;
            }
            set
            {
                if (_news_isDeleted != value)
                {
                    Onnews_isDeletedChanging(value);
                    ReportPropertyChanging("news_isDeleted");
                    _news_isDeleted = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("news_isDeleted");
                    Onnews_isDeletedChanged();
                }
            }
        }
        private global::System.Boolean _news_isDeleted;
        partial void Onnews_isDeletedChanging(global::System.Boolean value);
        partial void Onnews_isDeletedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean news_isOnIndex
        {
            get
            {
                return _news_isOnIndex;
            }
            set
            {
                if (_news_isOnIndex != value)
                {
                    Onnews_isOnIndexChanging(value);
                    ReportPropertyChanging("news_isOnIndex");
                    _news_isOnIndex = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("news_isOnIndex");
                    Onnews_isOnIndexChanged();
                }
            }
        }
        private global::System.Boolean _news_isOnIndex;
        partial void Onnews_isOnIndexChanging(global::System.Boolean value);
        partial void Onnews_isOnIndexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String news_image
        {
            get
            {
                return _news_image;
            }
            set
            {
                if (_news_image != value)
                {
                    Onnews_imageChanging(value);
                    ReportPropertyChanging("news_image");
                    _news_image = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("news_image");
                    Onnews_imageChanged();
                }
            }
        }
        private global::System.String _news_image;
        partial void Onnews_imageChanging(global::System.String value);
        partial void Onnews_imageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 news_click_count
        {
            get
            {
                return _news_click_count;
            }
            set
            {
                if (_news_click_count != value)
                {
                    Onnews_click_countChanging(value);
                    ReportPropertyChanging("news_click_count");
                    _news_click_count = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("news_click_count");
                    Onnews_click_countChanged();
                }
            }
        }
        private global::System.Int32 _news_click_count;
        partial void Onnews_click_countChanging(global::System.Int32 value);
        partial void Onnews_click_countChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String news_content
        {
            get
            {
                return _news_content;
            }
            set
            {
                if (_news_content != value)
                {
                    Onnews_contentChanging(value);
                    ReportPropertyChanging("news_content");
                    _news_content = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("news_content");
                    Onnews_contentChanged();
                }
            }
        }
        private global::System.String _news_content;
        partial void Onnews_contentChanging(global::System.String value);
        partial void Onnews_contentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid news_author
        {
            get
            {
                return _news_author;
            }
            set
            {
                if (_news_author != value)
                {
                    Onnews_authorChanging(value);
                    ReportPropertyChanging("news_author");
                    _news_author = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("news_author");
                    Onnews_authorChanged();
                }
            }
        }
        private global::System.Guid _news_author;
        partial void Onnews_authorChanging(global::System.Guid value);
        partial void Onnews_authorChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="avfun_DAL_model", Name="COURSE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COURSE : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 COURSE 对象。
        /// </summary>
        /// <param name="c_id">c_id 属性的初始值。</param>
        /// <param name="course_id">course_id 属性的初始值。</param>
        /// <param name="course_name">course_name 属性的初始值。</param>
        /// <param name="course_intro">course_intro 属性的初始值。</param>
        /// <param name="course_price">course_price 属性的初始值。</param>
        /// <param name="course_robot_link">course_robot_link 属性的初始值。</param>
        /// <param name="course_begin_date">course_begin_date 属性的初始值。</param>
        /// <param name="course_isDeleted">course_isDeleted 属性的初始值。</param>
        /// <param name="course_timestamp">course_timestamp 属性的初始值。</param>
        public static COURSE CreateCOURSE(global::System.Int32 c_id, global::System.Guid course_id, global::System.String course_name, global::System.String course_intro, global::System.Double course_price, global::System.String course_robot_link, global::System.DateTime course_begin_date, global::System.Boolean course_isDeleted, global::System.Byte[] course_timestamp)
        {
            COURSE cOURSE = new COURSE();
            cOURSE.c_id = c_id;
            cOURSE.course_id = course_id;
            cOURSE.course_name = course_name;
            cOURSE.course_intro = course_intro;
            cOURSE.course_price = course_price;
            cOURSE.course_robot_link = course_robot_link;
            cOURSE.course_begin_date = course_begin_date;
            cOURSE.course_isDeleted = course_isDeleted;
            cOURSE.course_timestamp = course_timestamp;
            return cOURSE;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 c_id
        {
            get
            {
                return _c_id;
            }
            set
            {
                Onc_idChanging(value);
                ReportPropertyChanging("c_id");
                _c_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("c_id");
                Onc_idChanged();
            }
        }
        private global::System.Int32 _c_id;
        partial void Onc_idChanging(global::System.Int32 value);
        partial void Onc_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid course_id
        {
            get
            {
                return _course_id;
            }
            set
            {
                if (_course_id != value)
                {
                    Oncourse_idChanging(value);
                    ReportPropertyChanging("course_id");
                    _course_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("course_id");
                    Oncourse_idChanged();
                }
            }
        }
        private global::System.Guid _course_id;
        partial void Oncourse_idChanging(global::System.Guid value);
        partial void Oncourse_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String course_name
        {
            get
            {
                return _course_name;
            }
            set
            {
                Oncourse_nameChanging(value);
                ReportPropertyChanging("course_name");
                _course_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("course_name");
                Oncourse_nameChanged();
            }
        }
        private global::System.String _course_name;
        partial void Oncourse_nameChanging(global::System.String value);
        partial void Oncourse_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String course_intro
        {
            get
            {
                return _course_intro;
            }
            set
            {
                Oncourse_introChanging(value);
                ReportPropertyChanging("course_intro");
                _course_intro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("course_intro");
                Oncourse_introChanged();
            }
        }
        private global::System.String _course_intro;
        partial void Oncourse_introChanging(global::System.String value);
        partial void Oncourse_introChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double course_price
        {
            get
            {
                return _course_price;
            }
            set
            {
                Oncourse_priceChanging(value);
                ReportPropertyChanging("course_price");
                _course_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("course_price");
                Oncourse_priceChanged();
            }
        }
        private global::System.Double _course_price;
        partial void Oncourse_priceChanging(global::System.Double value);
        partial void Oncourse_priceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String course_robot_link
        {
            get
            {
                return _course_robot_link;
            }
            set
            {
                Oncourse_robot_linkChanging(value);
                ReportPropertyChanging("course_robot_link");
                _course_robot_link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("course_robot_link");
                Oncourse_robot_linkChanged();
            }
        }
        private global::System.String _course_robot_link;
        partial void Oncourse_robot_linkChanging(global::System.String value);
        partial void Oncourse_robot_linkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime course_begin_date
        {
            get
            {
                return _course_begin_date;
            }
            set
            {
                Oncourse_begin_dateChanging(value);
                ReportPropertyChanging("course_begin_date");
                _course_begin_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("course_begin_date");
                Oncourse_begin_dateChanged();
            }
        }
        private global::System.DateTime _course_begin_date;
        partial void Oncourse_begin_dateChanging(global::System.DateTime value);
        partial void Oncourse_begin_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean course_isDeleted
        {
            get
            {
                return _course_isDeleted;
            }
            set
            {
                Oncourse_isDeletedChanging(value);
                ReportPropertyChanging("course_isDeleted");
                _course_isDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("course_isDeleted");
                Oncourse_isDeletedChanged();
            }
        }
        private global::System.Boolean _course_isDeleted;
        partial void Oncourse_isDeletedChanging(global::System.Boolean value);
        partial void Oncourse_isDeletedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] course_timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_course_timestamp);
            }
            set
            {
                Oncourse_timestampChanging(value);
                ReportPropertyChanging("course_timestamp");
                _course_timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("course_timestamp");
                Oncourse_timestampChanged();
            }
        }
        private global::System.Byte[] _course_timestamp;
        partial void Oncourse_timestampChanging(global::System.Byte[] value);
        partial void Oncourse_timestampChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("avfun_DAL_model", "FK_ORDER_COURSE", "ORDER")]
        public EntityCollection<ORDER> ORDER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ORDER>("avfun_DAL_model.FK_ORDER_COURSE", "ORDER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ORDER>("avfun_DAL_model.FK_ORDER_COURSE", "ORDER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="avfun_DAL_model", Name="NEWS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NEWS : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 NEWS 对象。
        /// </summary>
        /// <param name="n_id">n_id 属性的初始值。</param>
        /// <param name="news_id">news_id 属性的初始值。</param>
        /// <param name="news_title">news_title 属性的初始值。</param>
        /// <param name="news_content">news_content 属性的初始值。</param>
        /// <param name="news_author">news_author 属性的初始值。</param>
        /// <param name="news_publish_date">news_publish_date 属性的初始值。</param>
        /// <param name="news_isDeleted">news_isDeleted 属性的初始值。</param>
        /// <param name="news_isOnIndex">news_isOnIndex 属性的初始值。</param>
        /// <param name="news_image">news_image 属性的初始值。</param>
        /// <param name="news_click_count">news_click_count 属性的初始值。</param>
        /// <param name="news_timestamp">news_timestamp 属性的初始值。</param>
        public static NEWS CreateNEWS(global::System.Int32 n_id, global::System.Guid news_id, global::System.String news_title, global::System.String news_content, global::System.Guid news_author, global::System.DateTime news_publish_date, global::System.Boolean news_isDeleted, global::System.Boolean news_isOnIndex, global::System.String news_image, global::System.Int32 news_click_count, global::System.Byte[] news_timestamp)
        {
            NEWS nEWS = new NEWS();
            nEWS.n_id = n_id;
            nEWS.news_id = news_id;
            nEWS.news_title = news_title;
            nEWS.news_content = news_content;
            nEWS.news_author = news_author;
            nEWS.news_publish_date = news_publish_date;
            nEWS.news_isDeleted = news_isDeleted;
            nEWS.news_isOnIndex = news_isOnIndex;
            nEWS.news_image = news_image;
            nEWS.news_click_count = news_click_count;
            nEWS.news_timestamp = news_timestamp;
            return nEWS;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 n_id
        {
            get
            {
                return _n_id;
            }
            set
            {
                Onn_idChanging(value);
                ReportPropertyChanging("n_id");
                _n_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("n_id");
                Onn_idChanged();
            }
        }
        private global::System.Int32 _n_id;
        partial void Onn_idChanging(global::System.Int32 value);
        partial void Onn_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid news_id
        {
            get
            {
                return _news_id;
            }
            set
            {
                if (_news_id != value)
                {
                    Onnews_idChanging(value);
                    ReportPropertyChanging("news_id");
                    _news_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("news_id");
                    Onnews_idChanged();
                }
            }
        }
        private global::System.Guid _news_id;
        partial void Onnews_idChanging(global::System.Guid value);
        partial void Onnews_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String news_title
        {
            get
            {
                return _news_title;
            }
            set
            {
                Onnews_titleChanging(value);
                ReportPropertyChanging("news_title");
                _news_title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("news_title");
                Onnews_titleChanged();
            }
        }
        private global::System.String _news_title;
        partial void Onnews_titleChanging(global::System.String value);
        partial void Onnews_titleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String news_content
        {
            get
            {
                return _news_content;
            }
            set
            {
                Onnews_contentChanging(value);
                ReportPropertyChanging("news_content");
                _news_content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("news_content");
                Onnews_contentChanged();
            }
        }
        private global::System.String _news_content;
        partial void Onnews_contentChanging(global::System.String value);
        partial void Onnews_contentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid news_author
        {
            get
            {
                return _news_author;
            }
            set
            {
                Onnews_authorChanging(value);
                ReportPropertyChanging("news_author");
                _news_author = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("news_author");
                Onnews_authorChanged();
            }
        }
        private global::System.Guid _news_author;
        partial void Onnews_authorChanging(global::System.Guid value);
        partial void Onnews_authorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime news_publish_date
        {
            get
            {
                return _news_publish_date;
            }
            set
            {
                Onnews_publish_dateChanging(value);
                ReportPropertyChanging("news_publish_date");
                _news_publish_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("news_publish_date");
                Onnews_publish_dateChanged();
            }
        }
        private global::System.DateTime _news_publish_date;
        partial void Onnews_publish_dateChanging(global::System.DateTime value);
        partial void Onnews_publish_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean news_isDeleted
        {
            get
            {
                return _news_isDeleted;
            }
            set
            {
                Onnews_isDeletedChanging(value);
                ReportPropertyChanging("news_isDeleted");
                _news_isDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("news_isDeleted");
                Onnews_isDeletedChanged();
            }
        }
        private global::System.Boolean _news_isDeleted;
        partial void Onnews_isDeletedChanging(global::System.Boolean value);
        partial void Onnews_isDeletedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean news_isOnIndex
        {
            get
            {
                return _news_isOnIndex;
            }
            set
            {
                Onnews_isOnIndexChanging(value);
                ReportPropertyChanging("news_isOnIndex");
                _news_isOnIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("news_isOnIndex");
                Onnews_isOnIndexChanged();
            }
        }
        private global::System.Boolean _news_isOnIndex;
        partial void Onnews_isOnIndexChanging(global::System.Boolean value);
        partial void Onnews_isOnIndexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String news_image
        {
            get
            {
                return _news_image;
            }
            set
            {
                Onnews_imageChanging(value);
                ReportPropertyChanging("news_image");
                _news_image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("news_image");
                Onnews_imageChanged();
            }
        }
        private global::System.String _news_image;
        partial void Onnews_imageChanging(global::System.String value);
        partial void Onnews_imageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 news_click_count
        {
            get
            {
                return _news_click_count;
            }
            set
            {
                Onnews_click_countChanging(value);
                ReportPropertyChanging("news_click_count");
                _news_click_count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("news_click_count");
                Onnews_click_countChanged();
            }
        }
        private global::System.Int32 _news_click_count;
        partial void Onnews_click_countChanging(global::System.Int32 value);
        partial void Onnews_click_countChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] news_timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_news_timestamp);
            }
            set
            {
                Onnews_timestampChanging(value);
                ReportPropertyChanging("news_timestamp");
                _news_timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_timestamp");
                Onnews_timestampChanged();
            }
        }
        private global::System.Byte[] _news_timestamp;
        partial void Onnews_timestampChanging(global::System.Byte[] value);
        partial void Onnews_timestampChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("avfun_DAL_model", "FK_NEWS_ADMIN", "ADMIN")]
        public ADMIN ADMIN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADMIN>("avfun_DAL_model.FK_NEWS_ADMIN", "ADMIN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADMIN>("avfun_DAL_model.FK_NEWS_ADMIN", "ADMIN").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ADMIN> ADMINReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADMIN>("avfun_DAL_model.FK_NEWS_ADMIN", "ADMIN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ADMIN>("avfun_DAL_model.FK_NEWS_ADMIN", "ADMIN", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("avfun_DAL_model", "FK_REVIEW_NEWS", "REVIEW")]
        public EntityCollection<REVIEW> REVIEW
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<REVIEW>("avfun_DAL_model.FK_REVIEW_NEWS", "REVIEW");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<REVIEW>("avfun_DAL_model.FK_REVIEW_NEWS", "REVIEW", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="avfun_DAL_model", Name="ORDER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ORDER : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ORDER 对象。
        /// </summary>
        /// <param name="o_id">o_id 属性的初始值。</param>
        /// <param name="order_id">order_id 属性的初始值。</param>
        /// <param name="order_date">order_date 属性的初始值。</param>
        /// <param name="order_price">order_price 属性的初始值。</param>
        /// <param name="order_isPaid">order_isPaid 属性的初始值。</param>
        /// <param name="order_isDeleted">order_isDeleted 属性的初始值。</param>
        /// <param name="order_user">order_user 属性的初始值。</param>
        /// <param name="order_course">order_course 属性的初始值。</param>
        /// <param name="order_timestamp">order_timestamp 属性的初始值。</param>
        public static ORDER CreateORDER(global::System.Int32 o_id, global::System.Guid order_id, global::System.DateTime order_date, global::System.Double order_price, global::System.Boolean order_isPaid, global::System.Boolean order_isDeleted, global::System.Guid order_user, global::System.Guid order_course, global::System.Byte[] order_timestamp)
        {
            ORDER oRDER = new ORDER();
            oRDER.o_id = o_id;
            oRDER.order_id = order_id;
            oRDER.order_date = order_date;
            oRDER.order_price = order_price;
            oRDER.order_isPaid = order_isPaid;
            oRDER.order_isDeleted = order_isDeleted;
            oRDER.order_user = order_user;
            oRDER.order_course = order_course;
            oRDER.order_timestamp = order_timestamp;
            return oRDER;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 o_id
        {
            get
            {
                return _o_id;
            }
            set
            {
                Ono_idChanging(value);
                ReportPropertyChanging("o_id");
                _o_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("o_id");
                Ono_idChanged();
            }
        }
        private global::System.Int32 _o_id;
        partial void Ono_idChanging(global::System.Int32 value);
        partial void Ono_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid order_id
        {
            get
            {
                return _order_id;
            }
            set
            {
                if (_order_id != value)
                {
                    Onorder_idChanging(value);
                    ReportPropertyChanging("order_id");
                    _order_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("order_id");
                    Onorder_idChanged();
                }
            }
        }
        private global::System.Guid _order_id;
        partial void Onorder_idChanging(global::System.Guid value);
        partial void Onorder_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime order_date
        {
            get
            {
                return _order_date;
            }
            set
            {
                Onorder_dateChanging(value);
                ReportPropertyChanging("order_date");
                _order_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_date");
                Onorder_dateChanged();
            }
        }
        private global::System.DateTime _order_date;
        partial void Onorder_dateChanging(global::System.DateTime value);
        partial void Onorder_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double order_price
        {
            get
            {
                return _order_price;
            }
            set
            {
                Onorder_priceChanging(value);
                ReportPropertyChanging("order_price");
                _order_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_price");
                Onorder_priceChanged();
            }
        }
        private global::System.Double _order_price;
        partial void Onorder_priceChanging(global::System.Double value);
        partial void Onorder_priceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean order_isPaid
        {
            get
            {
                return _order_isPaid;
            }
            set
            {
                Onorder_isPaidChanging(value);
                ReportPropertyChanging("order_isPaid");
                _order_isPaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_isPaid");
                Onorder_isPaidChanged();
            }
        }
        private global::System.Boolean _order_isPaid;
        partial void Onorder_isPaidChanging(global::System.Boolean value);
        partial void Onorder_isPaidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean order_isDeleted
        {
            get
            {
                return _order_isDeleted;
            }
            set
            {
                Onorder_isDeletedChanging(value);
                ReportPropertyChanging("order_isDeleted");
                _order_isDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_isDeleted");
                Onorder_isDeletedChanged();
            }
        }
        private global::System.Boolean _order_isDeleted;
        partial void Onorder_isDeletedChanging(global::System.Boolean value);
        partial void Onorder_isDeletedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid order_user
        {
            get
            {
                return _order_user;
            }
            set
            {
                Onorder_userChanging(value);
                ReportPropertyChanging("order_user");
                _order_user = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_user");
                Onorder_userChanged();
            }
        }
        private global::System.Guid _order_user;
        partial void Onorder_userChanging(global::System.Guid value);
        partial void Onorder_userChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid order_course
        {
            get
            {
                return _order_course;
            }
            set
            {
                Onorder_courseChanging(value);
                ReportPropertyChanging("order_course");
                _order_course = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_course");
                Onorder_courseChanged();
            }
        }
        private global::System.Guid _order_course;
        partial void Onorder_courseChanging(global::System.Guid value);
        partial void Onorder_courseChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] order_timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_order_timestamp);
            }
            set
            {
                Onorder_timestampChanging(value);
                ReportPropertyChanging("order_timestamp");
                _order_timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("order_timestamp");
                Onorder_timestampChanged();
            }
        }
        private global::System.Byte[] _order_timestamp;
        partial void Onorder_timestampChanging(global::System.Byte[] value);
        partial void Onorder_timestampChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("avfun_DAL_model", "FK_ORDER_COURSE", "COURSE")]
        public COURSE COURSE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COURSE>("avfun_DAL_model.FK_ORDER_COURSE", "COURSE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COURSE>("avfun_DAL_model.FK_ORDER_COURSE", "COURSE").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<COURSE> COURSEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COURSE>("avfun_DAL_model.FK_ORDER_COURSE", "COURSE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<COURSE>("avfun_DAL_model.FK_ORDER_COURSE", "COURSE", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("avfun_DAL_model", "FK_ORDER_USER", "USER")]
        public USER USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("avfun_DAL_model.FK_ORDER_USER", "USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("avfun_DAL_model.FK_ORDER_USER", "USER").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USER> USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("avfun_DAL_model.FK_ORDER_USER", "USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USER>("avfun_DAL_model.FK_ORDER_USER", "USER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="avfun_DAL_model", Name="REVIEW")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class REVIEW : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 REVIEW 对象。
        /// </summary>
        /// <param name="r_id">r_id 属性的初始值。</param>
        /// <param name="review_id">review_id 属性的初始值。</param>
        /// <param name="review_content">review_content 属性的初始值。</param>
        /// <param name="review_author">review_author 属性的初始值。</param>
        /// <param name="review_publish_date">review_publish_date 属性的初始值。</param>
        /// <param name="review_isDeleted">review_isDeleted 属性的初始值。</param>
        /// <param name="review_news">review_news 属性的初始值。</param>
        /// <param name="review_timestamp">review_timestamp 属性的初始值。</param>
        public static REVIEW CreateREVIEW(global::System.Int32 r_id, global::System.Guid review_id, global::System.String review_content, global::System.Guid review_author, global::System.DateTime review_publish_date, global::System.Boolean review_isDeleted, global::System.Guid review_news, global::System.Byte[] review_timestamp)
        {
            REVIEW rEVIEW = new REVIEW();
            rEVIEW.r_id = r_id;
            rEVIEW.review_id = review_id;
            rEVIEW.review_content = review_content;
            rEVIEW.review_author = review_author;
            rEVIEW.review_publish_date = review_publish_date;
            rEVIEW.review_isDeleted = review_isDeleted;
            rEVIEW.review_news = review_news;
            rEVIEW.review_timestamp = review_timestamp;
            return rEVIEW;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 r_id
        {
            get
            {
                return _r_id;
            }
            set
            {
                Onr_idChanging(value);
                ReportPropertyChanging("r_id");
                _r_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("r_id");
                Onr_idChanged();
            }
        }
        private global::System.Int32 _r_id;
        partial void Onr_idChanging(global::System.Int32 value);
        partial void Onr_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid review_id
        {
            get
            {
                return _review_id;
            }
            set
            {
                if (_review_id != value)
                {
                    Onreview_idChanging(value);
                    ReportPropertyChanging("review_id");
                    _review_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("review_id");
                    Onreview_idChanged();
                }
            }
        }
        private global::System.Guid _review_id;
        partial void Onreview_idChanging(global::System.Guid value);
        partial void Onreview_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String review_content
        {
            get
            {
                return _review_content;
            }
            set
            {
                Onreview_contentChanging(value);
                ReportPropertyChanging("review_content");
                _review_content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("review_content");
                Onreview_contentChanged();
            }
        }
        private global::System.String _review_content;
        partial void Onreview_contentChanging(global::System.String value);
        partial void Onreview_contentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid review_author
        {
            get
            {
                return _review_author;
            }
            set
            {
                Onreview_authorChanging(value);
                ReportPropertyChanging("review_author");
                _review_author = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("review_author");
                Onreview_authorChanged();
            }
        }
        private global::System.Guid _review_author;
        partial void Onreview_authorChanging(global::System.Guid value);
        partial void Onreview_authorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime review_publish_date
        {
            get
            {
                return _review_publish_date;
            }
            set
            {
                Onreview_publish_dateChanging(value);
                ReportPropertyChanging("review_publish_date");
                _review_publish_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("review_publish_date");
                Onreview_publish_dateChanged();
            }
        }
        private global::System.DateTime _review_publish_date;
        partial void Onreview_publish_dateChanging(global::System.DateTime value);
        partial void Onreview_publish_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean review_isDeleted
        {
            get
            {
                return _review_isDeleted;
            }
            set
            {
                Onreview_isDeletedChanging(value);
                ReportPropertyChanging("review_isDeleted");
                _review_isDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("review_isDeleted");
                Onreview_isDeletedChanged();
            }
        }
        private global::System.Boolean _review_isDeleted;
        partial void Onreview_isDeletedChanging(global::System.Boolean value);
        partial void Onreview_isDeletedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid review_news
        {
            get
            {
                return _review_news;
            }
            set
            {
                Onreview_newsChanging(value);
                ReportPropertyChanging("review_news");
                _review_news = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("review_news");
                Onreview_newsChanged();
            }
        }
        private global::System.Guid _review_news;
        partial void Onreview_newsChanging(global::System.Guid value);
        partial void Onreview_newsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] review_timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_review_timestamp);
            }
            set
            {
                Onreview_timestampChanging(value);
                ReportPropertyChanging("review_timestamp");
                _review_timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("review_timestamp");
                Onreview_timestampChanged();
            }
        }
        private global::System.Byte[] _review_timestamp;
        partial void Onreview_timestampChanging(global::System.Byte[] value);
        partial void Onreview_timestampChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("avfun_DAL_model", "FK_REVIEW_NEWS", "NEWS")]
        public NEWS NEWS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NEWS>("avfun_DAL_model.FK_REVIEW_NEWS", "NEWS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NEWS>("avfun_DAL_model.FK_REVIEW_NEWS", "NEWS").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NEWS> NEWSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NEWS>("avfun_DAL_model.FK_REVIEW_NEWS", "NEWS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NEWS>("avfun_DAL_model.FK_REVIEW_NEWS", "NEWS", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("avfun_DAL_model", "FK_REVIEW_USER", "USER")]
        public USER USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("avfun_DAL_model.FK_REVIEW_USER", "USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("avfun_DAL_model.FK_REVIEW_USER", "USER").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USER> USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("avfun_DAL_model.FK_REVIEW_USER", "USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USER>("avfun_DAL_model.FK_REVIEW_USER", "USER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="avfun_DAL_model", Name="USER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USER : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 USER 对象。
        /// </summary>
        /// <param name="u_id">u_id 属性的初始值。</param>
        /// <param name="user_id">user_id 属性的初始值。</param>
        /// <param name="user_account">user_account 属性的初始值。</param>
        /// <param name="user_password">user_password 属性的初始值。</param>
        /// <param name="user_nickname">user_nickname 属性的初始值。</param>
        /// <param name="user_sex">user_sex 属性的初始值。</param>
        /// <param name="user_head">user_head 属性的初始值。</param>
        /// <param name="user_isDeleted">user_isDeleted 属性的初始值。</param>
        /// <param name="user_isChecked">user_isChecked 属性的初始值。</param>
        /// <param name="user_last_login_time">user_last_login_time 属性的初始值。</param>
        /// <param name="user_last_login_ip">user_last_login_ip 属性的初始值。</param>
        /// <param name="user_money">user_money 属性的初始值。</param>
        /// <param name="user_introduction">user_introduction 属性的初始值。</param>
        /// <param name="user_timestamp">user_timestamp 属性的初始值。</param>
        /// <param name="user_verify_code">user_verify_code 属性的初始值。</param>
        public static USER CreateUSER(global::System.Int32 u_id, global::System.Guid user_id, global::System.String user_account, global::System.String user_password, global::System.String user_nickname, global::System.Boolean user_sex, global::System.String user_head, global::System.Boolean user_isDeleted, global::System.Boolean user_isChecked, global::System.DateTime user_last_login_time, global::System.String user_last_login_ip, global::System.Double user_money, global::System.String user_introduction, global::System.Byte[] user_timestamp, global::System.Guid user_verify_code)
        {
            USER uSER = new USER();
            uSER.u_id = u_id;
            uSER.user_id = user_id;
            uSER.user_account = user_account;
            uSER.user_password = user_password;
            uSER.user_nickname = user_nickname;
            uSER.user_sex = user_sex;
            uSER.user_head = user_head;
            uSER.user_isDeleted = user_isDeleted;
            uSER.user_isChecked = user_isChecked;
            uSER.user_last_login_time = user_last_login_time;
            uSER.user_last_login_ip = user_last_login_ip;
            uSER.user_money = user_money;
            uSER.user_introduction = user_introduction;
            uSER.user_timestamp = user_timestamp;
            uSER.user_verify_code = user_verify_code;
            return uSER;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 u_id
        {
            get
            {
                return _u_id;
            }
            set
            {
                Onu_idChanging(value);
                ReportPropertyChanging("u_id");
                _u_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("u_id");
                Onu_idChanged();
            }
        }
        private global::System.Int32 _u_id;
        partial void Onu_idChanging(global::System.Int32 value);
        partial void Onu_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Guid _user_id;
        partial void Onuser_idChanging(global::System.Guid value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_account
        {
            get
            {
                return _user_account;
            }
            set
            {
                Onuser_accountChanging(value);
                ReportPropertyChanging("user_account");
                _user_account = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_account");
                Onuser_accountChanged();
            }
        }
        private global::System.String _user_account;
        partial void Onuser_accountChanging(global::System.String value);
        partial void Onuser_accountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_password
        {
            get
            {
                return _user_password;
            }
            set
            {
                Onuser_passwordChanging(value);
                ReportPropertyChanging("user_password");
                _user_password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_password");
                Onuser_passwordChanged();
            }
        }
        private global::System.String _user_password;
        partial void Onuser_passwordChanging(global::System.String value);
        partial void Onuser_passwordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_nickname
        {
            get
            {
                return _user_nickname;
            }
            set
            {
                Onuser_nicknameChanging(value);
                ReportPropertyChanging("user_nickname");
                _user_nickname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_nickname");
                Onuser_nicknameChanged();
            }
        }
        private global::System.String _user_nickname;
        partial void Onuser_nicknameChanging(global::System.String value);
        partial void Onuser_nicknameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean user_sex
        {
            get
            {
                return _user_sex;
            }
            set
            {
                Onuser_sexChanging(value);
                ReportPropertyChanging("user_sex");
                _user_sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_sex");
                Onuser_sexChanged();
            }
        }
        private global::System.Boolean _user_sex;
        partial void Onuser_sexChanging(global::System.Boolean value);
        partial void Onuser_sexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_head
        {
            get
            {
                return _user_head;
            }
            set
            {
                Onuser_headChanging(value);
                ReportPropertyChanging("user_head");
                _user_head = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_head");
                Onuser_headChanged();
            }
        }
        private global::System.String _user_head;
        partial void Onuser_headChanging(global::System.String value);
        partial void Onuser_headChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean user_isDeleted
        {
            get
            {
                return _user_isDeleted;
            }
            set
            {
                Onuser_isDeletedChanging(value);
                ReportPropertyChanging("user_isDeleted");
                _user_isDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_isDeleted");
                Onuser_isDeletedChanged();
            }
        }
        private global::System.Boolean _user_isDeleted;
        partial void Onuser_isDeletedChanging(global::System.Boolean value);
        partial void Onuser_isDeletedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean user_isChecked
        {
            get
            {
                return _user_isChecked;
            }
            set
            {
                Onuser_isCheckedChanging(value);
                ReportPropertyChanging("user_isChecked");
                _user_isChecked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_isChecked");
                Onuser_isCheckedChanged();
            }
        }
        private global::System.Boolean _user_isChecked;
        partial void Onuser_isCheckedChanging(global::System.Boolean value);
        partial void Onuser_isCheckedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime user_last_login_time
        {
            get
            {
                return _user_last_login_time;
            }
            set
            {
                Onuser_last_login_timeChanging(value);
                ReportPropertyChanging("user_last_login_time");
                _user_last_login_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_last_login_time");
                Onuser_last_login_timeChanged();
            }
        }
        private global::System.DateTime _user_last_login_time;
        partial void Onuser_last_login_timeChanging(global::System.DateTime value);
        partial void Onuser_last_login_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_last_login_ip
        {
            get
            {
                return _user_last_login_ip;
            }
            set
            {
                Onuser_last_login_ipChanging(value);
                ReportPropertyChanging("user_last_login_ip");
                _user_last_login_ip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_last_login_ip");
                Onuser_last_login_ipChanged();
            }
        }
        private global::System.String _user_last_login_ip;
        partial void Onuser_last_login_ipChanging(global::System.String value);
        partial void Onuser_last_login_ipChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double user_money
        {
            get
            {
                return _user_money;
            }
            set
            {
                Onuser_moneyChanging(value);
                ReportPropertyChanging("user_money");
                _user_money = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_money");
                Onuser_moneyChanged();
            }
        }
        private global::System.Double _user_money;
        partial void Onuser_moneyChanging(global::System.Double value);
        partial void Onuser_moneyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_introduction
        {
            get
            {
                return _user_introduction;
            }
            set
            {
                Onuser_introductionChanging(value);
                ReportPropertyChanging("user_introduction");
                _user_introduction = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_introduction");
                Onuser_introductionChanged();
            }
        }
        private global::System.String _user_introduction;
        partial void Onuser_introductionChanging(global::System.String value);
        partial void Onuser_introductionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] user_timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_user_timestamp);
            }
            set
            {
                Onuser_timestampChanging(value);
                ReportPropertyChanging("user_timestamp");
                _user_timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_timestamp");
                Onuser_timestampChanged();
            }
        }
        private global::System.Byte[] _user_timestamp;
        partial void Onuser_timestampChanging(global::System.Byte[] value);
        partial void Onuser_timestampChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid user_verify_code
        {
            get
            {
                return _user_verify_code;
            }
            set
            {
                Onuser_verify_codeChanging(value);
                ReportPropertyChanging("user_verify_code");
                _user_verify_code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_verify_code");
                Onuser_verify_codeChanged();
            }
        }
        private global::System.Guid _user_verify_code;
        partial void Onuser_verify_codeChanging(global::System.Guid value);
        partial void Onuser_verify_codeChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("avfun_DAL_model", "FK_ORDER_USER", "ORDER")]
        public EntityCollection<ORDER> ORDER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ORDER>("avfun_DAL_model.FK_ORDER_USER", "ORDER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ORDER>("avfun_DAL_model.FK_ORDER_USER", "ORDER", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("avfun_DAL_model", "FK_REVIEW_USER", "REVIEW")]
        public EntityCollection<REVIEW> REVIEW
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<REVIEW>("avfun_DAL_model.FK_REVIEW_USER", "REVIEW");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<REVIEW>("avfun_DAL_model.FK_REVIEW_USER", "REVIEW", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
